"""The committed samples must be exactly what the generator produces.

"Generated by script, never hand-written" is easy to claim and easy to
violate: someone tidies a sample by hand, the file drifts from the code, and
the repository now advertises output the system does not produce. That is a
small version of the same dishonesty this project is about.

So it is asserted rather than promised. Regenerate into a temp directory and
compare byte for byte.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

from generate_samples import SAMPLES, generate  # noqa: E402

COMMITTED = Path(__file__).resolve().parent.parent / "sample-outputs"


def test_every_declared_sample_is_committed():
    for name in SAMPLES:
        assert (COMMITTED / name).exists(), f"{name} is declared but not committed"


@pytest.mark.parametrize("name", SAMPLES)
def test_committed_sample_matches_a_fresh_generation(name, tmp_path):
    generate(tmp_path)

    assert (tmp_path / name).read_text() == (COMMITTED / name).read_text(), (
        f"{name} differs from what scripts/generate_samples.py produces. "
        f"Regenerate with: python scripts/generate_samples.py"
    )


def test_the_generator_runs_outside_the_suite(tmp_path):
    """``python scripts/generate_samples.py`` has to work from a plain shell.

    The suite's ``conftest`` sets the ingest and scheduler secrets, and
    ``deadman.service`` builds its WSGI app at import and refuses without them.
    So the generator passed here while the documented command failed for anyone
    who ran it — a regeneration step nobody can run is a hand-written sample
    with extra steps. Asserted in a subprocess with every ``DEADMAN_*``
    variable stripped, because that is the only place conftest cannot help.
    """
    env = {k: v for k, v in os.environ.items() if not k.startswith("DEADMAN_")}
    scripts = str(Path(__file__).resolve().parent.parent / "scripts")

    done = subprocess.run(
        [
            sys.executable,
            "-c",
            "import sys; sys.path.insert(0, sys.argv[1]);"
            "from pathlib import Path; import generate_samples;"
            "generate_samples.generate(Path(sys.argv[2]))",
            scripts,
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        env=env,
    )

    assert done.returncode == 0, done.stderr
    for name in SAMPLES:
        assert (tmp_path / name).exists()


def test_the_generator_is_deterministic(tmp_path):
    # Samples that change on every run cannot be diffed in review, so a real
    # behaviour change would be invisible inside the churn.
    first, second = tmp_path / "a", tmp_path / "b"
    generate(first)
    generate(second)

    for name in SAMPLES:
        assert (first / name).read_text() == (second / name).read_text()
